name: Build and Release
on:
  push:
    branches:
      - github-actions-automation
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: git clone -b dev https://github.com/vektor451/vekamp
      - name: Update repos
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y build-essential cmake libgtk-3-dev libgtk-4-dev
      - name: Change directory to vekamp
        run: cd vekamp
      - name: Configure using CMake
        run: cmake -S . -B build
      - name: Build makefile
        run: cmake
      - name: Make project
        run: make
